version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: appweb-php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: appweb-db
    environment:
      MYSQL_ROOT_PASSWORD: 04072006
      MYSQL_DATABASE: appweb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: appweb-pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 04072006
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
